### ISSUE TITLE
Execute the code with an error

### ISSUE THREAD

**Issue by hidonkey2018** [wesselb/ConvCNPs.jl#3]
I have tried to have a quick start by running the train.jl. However, it end up with an error 

ERROR: LoadError: UndefVarError: `CUDNN` not defined

The code run in the environment:

- Windows 11
- Nvidia RTX a1000 laptop gpu (driver version 536.67)
- Julia 1.9.2
- CUDA Toolkit 12.2

Thank you for your help.

**Comment by wesselb** [comment]
Hey @hidonkey2018! This package unfortunately is very much outdated and currently not maintained. If you’re willing to use Python, [we have a Python version of the package](https://github.com/wesselb/NeuralProcesses) that is currently more advanced. If you’d be willing to invest a little time in reviving this package by updating the dependencies to the latest versions, then of course contributions would be very much welcome.

**Comment by hidonkey2018** [comment]
Hi @wesselb. Thank you for your prompt reply. I am willing to use the Python version.  I am a newbie of Julia, If I gain more knowledge and experience of this language, I will take a try to sort it out. Anyway, thank for all your work.

**Comment by wesselb** [comment]
Thanks @hidonkey2018! Sorry for the trouble. We should be able to support you in using the Python version. :)

**Comment by hidonkey2018** [comment]
Thank a lot.
